# Generated by Django 5.0.11 on 2025-02-11 04:16

import bwf_components.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_active_version', models.CharField(default='0.0', max_length=15)),
                ('workflow_file', models.FileField(max_length=1000, upload_to=bwf_components.models.upload_to_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.IntegerField(default=1)),
                ('env_variables', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_function', models.BooleanField(default=True)),
                ('path_to_execute', models.CharField(blank=True, max_length=1000, null=True)),
                ('code_to_execute', models.TextField(default='print("Workflow action")')),
                ('options', models.JSONField()),
                ('input', models.JSONField()),
                ('output', models.JSONField()),
                ('version_number', models.IntegerField(default=1)),
                ('on_error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_callback', to='bwf_components.workflowaction')),
                ('on_success', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_callback', to='bwf_components.workflowaction')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variables', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'initial'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('ERROR', 'error')], default='PENDING', max_length=50)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='bwf_components.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwf_components.workflowaction')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowActionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.JSONField()),
                ('input', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'initial'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('ERROR', 'error')], default='PENDING', max_length=50)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_actions', to='bwf_components.workflowinstance')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bwf_components.workflowstepaction')),
                ('parent_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_actions', to='bwf_components.workflowstepaction')),
            ],
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='sub_actions',
            field=models.ManyToManyField(related_name='parent_actions', to='bwf_components.workflowstepaction'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='definition',
            field=models.ManyToManyField(to='bwf_components.workflowstepaction'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='main_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='bwf_components.workflowstepaction'),
        ),
    ]
