# Generated by Django 5.2 on 2025-05-09 02:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'User',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_email')],
            },
        ),
        migrations.CreateModel(
            name='BWF_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'BWF Role',
                'constraints': [models.UniqueConstraint(fields=('system_name', 'name'), name='approval_unique_name_system')],
            },
        ),
    ]
