# Generated by Django 5.0.11 on 2025-02-14 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path_to_execute', models.CharField(blank=True, max_length=1000, null=True)),
                ('script', models.TextField(default='print("Workflow action")')),
                ('base_input', models.JSONField()),
                ('base_output', models.JSONField()),
                ('version_number', models.IntegerField(default=1)),
                ('version_name', models.CharField(default='0.0', max_length=15)),
                ('editable', models.BooleanField(default=True)),
                ('children_components', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('expression', models.TextField(default='')),
                ('json_value', models.JSONField()),
                ('index', models.SmallIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('STRING', 'string'), ('NUMBER', 'number'), ('ARRAY', 'array'), ('OBJECT', 'object'), ('BOOLEAN', 'boolean')], default='STRING', max_length=50)),
                ('value', models.TextField()),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OnComponentFail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RETRY', 'Retry'), ('IGNORE', 'Ignore'), ('TERMINATE', 'Terminate'), ('CUSTOM', 'Custom')], default='Retry', max_length=15)),
                ('max_retries', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('retry_interval', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('options', models.JSONField()),
                ('version_number', models.IntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='components.componentdefinition')),
            ],
        ),
    ]
