# Generated by Django 5.0.11 on 2025-02-14 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcomponent',
            name='parent_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='oncomponentfail',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.workflowcomponent'),
        ),
        migrations.AddField(
            model_name='componentoutput',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='components.workflowcomponent'),
        ),
        migrations.AddField(
            model_name='componentinput',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='components.workflowcomponent'),
        ),
    ]
