# Generated by Django 5.0.11 on 2025-02-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_componentdefinition_base_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncomponentfail',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_fail', to='components.workflowcomponent'),
        ),
        migrations.AlterField(
            model_name='oncomponentfail',
            name='type',
            field=models.CharField(choices=[('RETRY', 'Retry'), ('IGNORE', 'Ignore'), ('TERMINATE', 'Terminate'), ('CUSTOM', 'Custom')], default='RETRY', max_length=15),
        ),
    ]
