# Generated by Django 5.0.11 on 2025-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_oncomponentfail_num_retries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentoutput',
            name='data_type',
            field=models.CharField(choices=[('string', 'string'), ('number', 'number'), ('array', 'array'), ('object', 'object'), ('boolean', 'boolean')], default='string', max_length=50),
        ),
    ]
