# Generated by Django 5.0.11 on 2025-02-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_alter_componentoutput_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentoutput',
            name='key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
