# Generated by Django 5.0.11 on 2025-02-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_componentoutput_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentoutput',
            name='value',
        ),
        migrations.AddField(
            model_name='componentinput',
            name='data_type',
            field=models.CharField(choices=[('string', 'string'), ('number', 'number'), ('array', 'array'), ('object', 'object'), ('boolean', 'boolean')], default='string', max_length=50),
        ),
        migrations.AddField(
            model_name='componentoutput',
            name='json_value',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='componentoutput',
            name='many',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='componentinput',
            name='expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentinput',
            name='json_value',
            field=models.JSONField(default={}),
        ),
    ]
