# Generated by Django 5.0.11 on 2025-02-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_alter_workflowcomponent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdefinition',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
