# Generated by Django 5.0.11 on 2025-03-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_componentdefinition_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowcomponent',
            name='definition',
        ),
        migrations.AddField(
            model_name='workflowcomponent',
            name='plugin_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
