# Generated by Django 5.0.11 on 2025-03-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_remove_workflowcomponent_definition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentoutput',
            name='component',
        ),
        migrations.DeleteModel(
            name='ComponentInput',
        ),
        migrations.DeleteModel(
            name='ComponentOutput',
        ),
    ]
