export const INPUT_TYPES = {
  TEXT: 'text',
  NUMBER: 'number',
  PASSWORD: 'password',
  EMAIL: 'email',
  DATE: 'date',
  TIME: 'time',
  DATETIME: 'datetime',
  SELECT: 'select',
  CHECK_BOX: 'checkbox',
  SELECT_BOXES: 'select-boxes',
  RADIO: 'radio',
  DATE_PICKER: 'date-picker',
  TIME_PICKER: 'time-picker',
  TEXT_AREA: 'textarea',
  MOBILE_NUMBER: 'tel',
  FILE_UPLOAD: 'file',
};
