export const LAYOUT_TYPES = {
  ROW_COLUMNS: 'row-columns',
  CONTAINER: 'container',
  SECTION: 'section',
  EDIT_GRID: 'edit-grid',
  COLUMN: 'column',
  DROPABLE: 'dropable',
  EDIT_DROPABLE: 'edit-dropable',
  CONTENT: 'content',
  HTML_CONTENT: 'htmlContent',
  GAP: 'gap',
  DIVIDER: 'divider',
  PANEL: 'panel',
  FIELD_SET: 'fieldset',
};
