# Generated by Django 5.0.11 on 2025-02-12 08:50

import bwf_components.workflow.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('current_active_version', models.CharField(default='0.0', max_length=15)),
                ('workflow_file', models.FileField(max_length=1000, upload_to=bwf_components.workflow.models.upload_to_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.IntegerField(default=1)),
                ('entrypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='components.workflowcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('data_type', models.CharField(choices=[('STRING', 'string'), ('NUMBER', 'number'), ('ARRAY', 'array'), ('OBJECT', 'object'), ('BOOLEAN', 'boolean'), ('SELECT', 'select'), ('MULTI_SELECT', 'multi_select'), ('FILE', 'file'), ('ANY', 'any')], default='STRING', max_length=50)),
                ('default_value', models.JSONField()),
                ('value', models.JSONField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input', to='workflow.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variables', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'initial'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('ERROR', 'error')], default='PENDING', max_length=50)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflow.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='components.workflowcomponent')),
                ('next_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_steps', to='components.workflowcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowActionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.JSONField()),
                ('input', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'initial'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('ERROR', 'error')], default='PENDING', max_length=50)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_actions', to='workflow.workflowinstance')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowstepaction')),
                ('parent_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_actions', to='workflow.workflowstepaction')),
            ],
        ),
    ]
