# Generated by Django 5.0.11 on 2025-02-14 06:39

import bwf_components.workflow.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='workflow_file',
            field=models.FileField(blank=True, max_length=1000, null=True, storage=django.core.files.storage.FileSystemStorage(location='/data/data/projects/spatial-layer-monitor/private-media'), upload_to=bwf_components.workflow.models.upload_to_path),
        ),
    ]
