# Generated by Django 5.0.11 on 2025-02-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_workflow_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='cluster',
        ),
        migrations.AddField(
            model_name='workflow',
            name='main_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_workflow', to='workflow.workflowcluster'),
        ),
        migrations.AddField(
            model_name='workflowcluster',
            name='main_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_clusters', to='workflow.workflow'),
        ),
    ]
