# Generated by Django 5.0.11 on 2025-02-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_remove_workflow_cluster_workflow_main_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinput',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workflowinput',
            name='default_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowinput',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
