# Generated by Django 5.0.11 on 2025-02-18 03:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflowinput_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 18, 11, 26, 32, 880098)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='error_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='error_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ActionLogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workflow.componentinstance')),
            ],
        ),
        migrations.CreateModel(
            name='JobQueueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR')], default='QUEUED')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_job', to='workflow.componentinstance')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_jobs', to='workflow.workflowinstance')),
            ],
        ),
    ]
