# Generated by Django 5.0.11 on 2025-02-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_componentinstance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='input',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='variables',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
