# Generated by Django 5.0.11 on 2025-02-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_componentinstance_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablevalue',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
