# Generated by Django 5.0.11 on 2025-02-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_alter_variablevalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablevalue',
            name='data_type',
            field=models.CharField(choices=[('string', 'string'), ('number', 'number'), ('array', 'array'), ('object', 'object'), ('boolean', 'boolean')], default='string', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowinput',
            name='data_type',
            field=models.CharField(choices=[('string', 'string'), ('number', 'number'), ('array', 'array'), ('object', 'object'), ('boolean', 'boolean'), ('select', 'select'), ('multi_select', 'multi_select'), ('file', 'file'), ('any', 'any')], default='string', max_length=50),
        ),
    ]
