# Generated by Django 5.0.11 on 2025-03-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_remove_componentinstance_parent_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentinstance',
            name='component',
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='component_id',
            field=models.CharField(default='default_1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_nodes', to='workflow.componentinstance'),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'initial'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('AWAITING_ACTION', 'awaiting_action'), ('ERROR', 'error')], default='PENDING', max_length=50),
        ),
    ]
