# Generated by Django 5.0.11 on 2025-03-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_workflowversion_applied_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='current_active_version',
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
