# Generated by Django 5.0.11 on 2025-03-19 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_remove_workflow_current_active_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversion',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_versions', to='workflow.workflowversion'),
        ),
    ]
