# Generated by Django 5.0.11 on 2025-03-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_workflowversion_parent_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowversion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
