# Generated by Django 5.0.11 on 2025-03-21 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_remove_workflowinstance_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflow.workflowversion'),
        ),
    ]
