# Generated by Django 5.2 on 2025-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_workflowinstance_workflow_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'initial'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('AWAITING_ACTION', 'awaiting_action'), ('ERROR', 'error'), ('TERMINATED', 'terminated')], default='PENDING', max_length=50),
        ),
    ]
