# Generated by Django 5.0.11 on 2025-03-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0017_workflowinstance_workflow_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'success'), ('ERROR', 'error'), ('PENDING', 'pending'), ('STARTED', 'started'), ('STOPPED', 'stopped'), ('RESTARTED', 'restarted')], default='STARTED', max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflow.componentinstance')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflow.workflowinstance')),
            ],
        ),
    ]
