# Generated by Django 5.0.11 on 2025-03-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_log', '0001_initial'),
        ('workflow', '0017_workflowinstance_workflow_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='component_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='workflow.componentinstance'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='workflow.workflowinstance'),
        ),
    ]
