# Generated by Django 5.2 on 2025-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_log', '0002_alter_actionlog_component_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'success'), ('ERROR', 'error'), ('PENDING', 'pending'), ('STARTED', 'started'), ('STOPPED', 'stopped'), ('RESTARTED', 'restarted'), ('TERMINATED', 'terminated')], default='STARTED', max_length=100),
        ),
    ]
